server:
  port: 8004
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liucm-it/spring-cloud-config.git
#           git仓库地址下的相对地址，可以配置多个，用,分割
#          search-paths: config-repo
#          公开仓库可以不用配置
#          username: yourname   # git仓库的账号
#          password: yourpass   # git仓库的密码
eureka:
  client:
    serviceUrl:
      # 注册中心eureka集群可用“,”配置多个 http://localhost:8002/eureka/,http://localhost:8002/eureka/
      defaultZone: http://localhost:8000/eureka/
